### ISSUE TITLE
Can't move sub loop task around ?

### ISSUE THREAD

**Issue by lcontami** [Exopy/exopy#131]
Error when trying to move a loop task in the tree menu (wait_condition is the name of a Conditional task, that is embedded in a Vb and the Vsd loop; I was trying to get the Vsd loop out of the Vb loop).
I can provide the task file but it contains instruments instructions.

```
ERROR: An uncaught exception occured : KeyError : 'Path root/VbLoop/Vsdloop/repeat/wait_condition is invalid, no node repeat in node Vsdloop' 
Traceback: File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\utils\widgets\qt_tree_widget.py", line 1074, in dropEvent data, False) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\utils\widgets\qt_tree_widget.py", line 601, in _insert node.insert_child(obj, index, data) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\measurement\workspace\measurement_edition.enaml", line 407, in insert_child obj.add_child_task(index, child) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 728, in add_child_task child.register_in_database() 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 838, in register_in_database child.register_in_database() 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 838, in register_in_database child.register_in_database()
 File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 242, in register_in_database self.write_in_database(entry, value) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 345, in write_in_database return self.database.set_value(self.path, value_name, value) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\database.py", line 109, in set_value node = self.go_to_path(node_path) 
File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\database.py", line 620, in go_to_path raise KeyError(err_str)
```

**Comment by MatthieuDartiailh** [comment]
Send the file anyway, I can edit it manually should I need to.

**Comment by lcontami** [comment]
[sweep_g_B_avg_034.meas.ini.zip](https://github.com/Exopy/exopy/files/1826250/sweep_g_B_avg_034.meas.ini.zip)

**Comment by MatthieuDartiailh** [comment]
I found the issue. I will get somebody to write a test for this during the sprint (or you can do it if you are in a hurry to get the fix in).

**Comment by lcontami** [comment]
[sweep_Vsd_IV_avg_021.meas.ini.zip](https://github.com/Exopy/exopy/files/1938046/sweep_Vsd_IV_avg_021.meas.ini.zip)
Here is the measurement file. The above error happens if you try to take Ibiais out of the RoundTrip loop.

Another bug, if I try to change the name of the Ibiais task to IbiaisLoop and then add a task in this loop, I get:

```
Traceback (most recent call last):
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\enaml\qt\qt_action.p
y", line 79, in on_triggered
    self.declaration.triggered(checked)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\enaml\core\declarati
ve_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\enaml\core\expressio
n_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\enaml\core\standard_
handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\utils\widgets\
list_editor.enaml", line 47, in f
    operations['add'](index, 'before')
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\ta
sk_editor.enaml", line 252, in add
    self.task.add_child_task(index, task)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\ba
se_tasks.py", line 728, in add_child_task
    child.register_in_database()
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\ba
se_tasks.py", line 242, in register_in_database
    self.write_in_database(entry, value)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\ba
se_tasks.py", line 345, in write_in_database
    return self.database.set_value(self.path, value_name, value)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\da
tabase.py", line 109, in set_value
    node = self.go_to_path(node_path)
  File "D:\Users\hqc\Anaconda2\envs\exopy\lib\site-packages\exopy\tasks\tasks\da
tabase.py", line 620, in go_to_path
    raise KeyError(err_str)
KeyError: 'Path root/RoundTrip/IbiaisLoop is invalid, no node IbiaisLoop in node
                        RoundTrip'
```

**Comment by MatthieuDartiailh** [comment]
From a quick count of the commits (on my cell phone so I may be wrong) 0.2.0.post6 does not contain the fix I wrote (that should cover both cases I believe).Could you check with latest master ?

**Comment by lcontami** [comment]
Ok for the first issue I thought I was up to date but I was not... Pffff. Then let me just create a new issue for the second bug.
